export const xlsxExpectedColumns = [
    "Location id", "Location name", "Address", "Average rating", "Total ratings", 
    "Google followers", "Google actions driving directions", "Google actions phone", 
    "Google actions website", "Google local post actions call to action", 
    "Google local post views search", "Google photos views customers", 
    "Google photos views merchant", "Google queries chain", "Google queries direct", 
    "Google queries indirect", "Google views maps", "Google views search", 
    "Google Phone 0", "Google Phone 1", "Google Phone 2", "Google Phone 3", 
    "Google Phone 4", "Google Phone 5", "Google Phone 6", "Google Phone 7", 
    "Google Phone 8", "Google Phone 9", "Google Phone 10", "Google Phone 11", 
    "Google Phone 12", "Google Phone 13", "Google Phone 14", "Google Phone 15", 
    "Google Phone 16", "Google Phone 17", "Google Phone 18", "Google Phone 19", 
    "Google Phone 20", "Google Phone 21", "Google Phone 22", "Google Phone 23", 
    "Google business impressions desktop maps", "Google business impressions desktop search", 
    "Google business impressions mobile maps", "Google business impressions mobile search", 
    "Google business conversations", "Google business direction requests", 
    "Google call clicks", "Google website clicks", "Google business bookings", 
    "Google business food orders", "Google business food menu clicks", 
    "Facebook page clicks", "Facebook page link clicks", "Facebook page other clicks", 
    "Facebook page photo views", "Facebook page video plays", "Facebook page other consumptions", 
    "Facebook page new likes", "Facebook page new unlikes", "Facebook page fans", 
    "Female fans aged 18-24", "Male fans aged 18-24", "Fans aged 18-24 with an undisclosed gender", 
    "Female fans aged 55-64", "Male fans aged 55-64", "Fans aged 55-64 with an undisclosed gender", 
    "Female fans aged 45-54", "Male fans aged 45-54", "Fans aged 45-54 with an undisclosed gender", 
    "Female fans aged 65+", "Male fans aged 65+", "Fans aged 65+ undisclosed gender", 
    "Female fans aged 13-17", "Male fans aged 13-17", "Fans aged 13-17 with an undisclosed gender", 
    "Female fans aged 35-44", "Male fans aged 35-44", "Fans aged 35-44 with an undisclosed gender", 
    "Female fans aged 25-34", "Male fans aged 25-34", "Fans aged 25-34 with an undisclosed gender", 
    "Facebook page views", "Facebook post or story from a Facebook page via unpaid distribution", 
    "Facebook post or story from a Facebook page via paid distribution", 
    "Facebook post or story from a Facebook page with social information", 
    "Facebook post from a Facebook page via unpaid distribution", 
    "Facebook post from a Facebook page via paid distribution", 
    "Facebook post from a Facebook page with social information", 
    "Facebook post entering a persons screen", "Facebook post that a person has interacted with", 
    "Facebook story on your page", "Yelp calls", "Yelp directions and map views", 
    "Yelp page views", "Yelp clicks", "Bing Search page desktop directions clicks", 
    "Bing Search page desktop photos clicks", "Bing Search page desktop website clicks", 
    "Bing Search page mobile directions clicks", "Bing Search page mobile website clicks", 
    "Bing Maps desktop views", "Bing Search page desktop views", "Bing Maps mobile views", 
    "Bing Search page mobile views"
];