import { Locator, Page } from "@playwright/test"

export class FeedViewComponent {
    readonly page: Page

    //event view
    readonly eventText              : Locator
    readonly replyTextArea          : Locator
    readonly suggestReplyButton     : Locator
    readonly sendReplyButton        : Locator
    readonly dynamicFieldsButton    : Locator
    readonly openAIReplyConfirmation: Locator

    //event list
    readonly eventCardList: Locator
    readonly eventIconList: Locator
    readonly eventCheckbox: (indexPosition: number) => Locator
    readonly eventCardItem: (indexPosition: number) => Locator

    constructor(page: Page) {
        this.page                    = page
        this.replyTextArea           = page.getByTestId('reply-textarea')
        this.eventText               = page.locator('.feed-text-media .context-pane-message')
        this.suggestReplyButton      = page.getByTestId('suggest-reply-btn')
        this.sendReplyButton         = page.locator('send-reply-btn')
        this.dynamicFieldsButton     = page.getByTestId('reply-dynamic-fields-btn')
        this.openAIReplyConfirmation = page.getByText('Autogenerated reply with OpenAI')
        this.eventCardList           = page.locator('mf-crossfeed-cards')
        this.eventIconList           = page.locator('[tbd]')
        this.eventCardItem           = (indexPosition: number) => this.eventCardList.locator('mf-crossfeed-card').nth(indexPosition)
        this.eventCheckbox           = (indexPosition: number) => page.locator(`#checkbox-${indexPosition} > .mat-checkbox-layout > .mat-checkbox-inner-container`)
    }
}